version: '3'
services:
  mongo:
    image: mongo:latest
    ports:
        - 27017:27017
    command: mongod --noauth
  webapp:
    build: .
    image: sms83/meanstackapp:latest
    depends_on:
      - "mongo"
    ports:
      - 4001:4001
